setup:
  type: list
  default: "staff, 3"

sidebar_side:
  default: right
  type: enum
  choices:
    - left
    - right

inherit_parent_sidebar:
  default: true

stick_on_scroll:
  default: true
  
enable_for_tags:
  default: true
  description: |
    Enable this component for tag pages: /tag/<b>tagname</b> 